# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Nombre', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'db_table': 'Libros',
                'managed': True,
            },
        ),
    ]
